### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by ursjoss** [fastluca/JRis#4]
Hi Gianluca

I'm currently looking into generating exports in RIS format and found your project.

You did not specify a license for JRis. Would you care to add one?

Thanks and cheers
Urs

**Comment by fastluca** [comment]
Hi and thank you for your interest in the project!
I will add a license asap.

Best Regards,
Gianluca

________________________________
Da: Urs Joss <notifications@github.com>
Inviato: lunedì 16 settembre 2019 07:24
A: fastluca/JRis <JRis@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: [fastluca/JRis] Project License (#4)


Hi Gianluca

I'm currently looking into generating exports in RIS format and found your project.

You did not specify a license for JRis. Would you care to add one?

Thanks and cheers
Urs

**Comment by fastluca** [comment]
@ursjoss License file added, I will close this issue.
Thank you!

**Comment by ursjoss** [comment]
Thanks @fastluca
