### ISSUE TITLE
Additional contribution

### ISSUE THREAD

**Issue by ursjoss** [fastluca/JRis#6]
Hi @fastluca 

As JRis is not published to maven central or bintray, I started my task of exporting a RIS file by copying your classes into my project. As I had slightly different use cases and am in the process of converting my project to kotlin, I started shaping your classes according to my requirements. That's also how I stumbled upon the small issues you just merged in #5. My goal is to eventually remove the copied (and modofied) classes and ideally pull in JRis through gradle dependencies.

The question now is, whether the additional changes I did in my copy of JRis are of interest to you. If so, I could provide a few pull requests. However, first I need to know if you like the direction I took so far.

Some of the major transformations I'm doing:

- conversion to kotlin
- have JRis not directly read or write files but work on collections providing the content (I'm using apache wicket and have the user download the file content via the browser).
- I replaced reflection with lambdas for setting/retrieving the data into/from the record.

If you'd like to have a look at the current state, you could check out https://github.com/ursjoss/scipamato/pull/126/

Alternative options to feeding back some or all of your changes into your repo would be to

- keep the modified copies in my project and completely detach it from your official JRis
- create a fork of JRis and maybe name it KRis (for kotlin).
- ...

Let me know if and how you'd like to proceed with this.

**Comment by fastluca** [comment]
Dear @ursjoss ,
sorry for the late response. Please see my remarks:
- in my opinion it could be of interest for some users in the community to have JRis as Java library and KRis as Kotlin one.
- Working on collections is a great future. What do you think about supporting both files and collections?
- Using lambda is for sure a better approach.

Thank you so much for your contribution!

**Comment by ursjoss** [comment]
Hi @fastluca. Thanks for your thoughts.

For the users of the library, it will not make a significant difference whether the library is written in Java or kotlin. With the exception that in kotlin, we can a add some syntactic sugar that makes it nicer to use from kotlin, but in the end both compile to jvm byte code.

I would also suggest to offer the api to directly work with files, but more as an extension.

This week, I will not get around to working on this, but the week after I might. I suggest tthat I play around with my fork. We can later discuss whether to integrate the experiment back into your repo and how to shape the api. Cheers

**Comment by ursjoss** [comment]
Hi @fastluca 

I am relatively happy with the state of my fork after finetuning it a bit over the week-end (using a locally deployed version in my main project, raising the test-coverage and adding the first draft of documentation etc.). The next step for me would be to publish it to be consumable via dependency management (gradle, maven).

The big question now would be how to proceed with my fork. Shall I keep it independently or would you be interested in integrating it into your repository? If the former, I would want to rename the package structure but I am free to go. If the latter, we could discuss on how to proceed.

Thanks for your thoughts. Best regards
Urs

**Comment by fastluca** [comment]
Dear @ursjoss 
Thank you for your updates. I think that it will be great if we integrate your work. Maybe we can collaborate to maintain an unique project, if for you it is acceptable.
Best Regards,
Gianluca

**Comment by ursjoss** [comment]
Hi @fastluca 

That's pretty cool and sounds like a plan. Thanks for your positive response. Let me suggest the following:

- Given that you're interested in re-integrating my fork, I will need to do some cleanup going into that direction.
- I will then create a pull request towards your repo. We can discuss the details in that pull request to bring it into shape to be integrated to both our liking.
- I presume you would make me a collaborator in your repo.
- I propose to do significant changes after the merge with pull requests and code reviews, so we can both have our stakes in shaping the common project.

A couple of questions up-front:
- did you already have a look at the current state of my fork? Does it still serve the needs of your use cases with JRis?
- do you already have some experience with kotlin - or are at least interested in working and co-maintaining a kotlin code base?

Or - in case you had a different idea in mind - how would you see the collaboration?

**Comment by fastluca** [comment]
Hi @ursjoss 
of course you will be a collaborator. I had a look on your work and I think it is great, you improved a lot JRis. About my needs, I created the library for a short term projects and actually I haven't any application, so my goal is to provide a good work for the community.
I haven't any experience with Kotlin but I will be happy to learn and to collaborate. I think that we can plan together how to move with JRis and divide tasks basing on our availability.

Best Regards,
Gianluca

**Comment by ursjoss** [comment]
Hi @fastluca 

That sounds like a good plan. I currently have an annoying issue that sonarcloud does not respect the test coverage provided by the integration tests in the `jrio-io` submodule.

See: https://sonarcloud.io/code?id=ursjoss_JRis&selected=ursjoss_JRis%3Asubprojects%2Fjris-io%2Fsrc

I have already spent quite some time trying to nail this down but so far without success. The next step would be to create a minimal example project where it is easier to pin-point the behavior. 

Besides I'm kinda waiting for the kordamp-gradle-plugin release 0.31.0, as it will simplify the detekt configuration, as it already brings some support with it.

But both issues are not critical and could also been tackled after the re-integration into your repo.

I am currently very busy both jobwise and with the whole end-of year stuff. I'll see when I'll have some time where we stand with the kordamp release and whether I'd first want to investigate the coverage issue or directly create the pull request to your repo.

**Comment by fastluca** [comment]
Dear @ursjoss,
I'm sorry, but I started an MBA program and I'm not able to dedicate the right time to this project. Sorry for that.

**Comment by ursjoss** [comment]
Hi @fastluca 

Thanks for your feedback. I understand an MBA will absorb you and will not leave much time for many other things. And prioritization is required of course.

I would therefore take the other approach and tweak my fork to become `KRis` in order to be able to go on with the project I actually want to use JRis/KRis for. Do you agree with this procedure?

**Comment by fastluca** [comment]
Hi @ursjoss 
thanks for your comprehension. Yes I totally agree with the approach suggested. Eventually I will write to you when I am availabe again to work on JRis.

**Comment by ursjoss** [comment]
Hi @fastluca 

Ok, so I'll move my repo towards `KRis`. All the best with your MBA!

**Comment by fastluca** [comment]
Hi ursjoss,
How are you? I've some free time in this period and I would like to contribute again to JRis/KRis project. Do you think that we could collaborate on that?

Best Regards,
Gianluca

________________________________
Da: Urs Joss <notifications@github.com>
Inviato: giovedì 12 dicembre 2019 08:16
A: fastluca/JRis <JRis@noreply.github.com>
Cc: Gianluca Colaianni <fast_luca@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [fastluca/JRis] Additional contribution (#6)


Hi @fastluca<https://github.com/fastluca>

That's pretty cool and sounds like a plan. Thanks for your positive response. Let me suggest the following:

  *   Given that you're interested in re-integrating my fork, I will need to do some cleanup going into that direction.
  *   I will then create a pull request towards your repo. We can discuss the details in that pull request to bring it into shape to be integrated to both our liking.
  *   I presume you would make me a collaborator in your repo.
  *   I propose to do significant changes after the merge with pull requests and code reviews, so we can both have our stakes in shaping the common project.

A couple of questions up-front:

  *   did you already have a look at the current state of my fork? Does it still serve the needs of your use cases with JRis?
  *   do you already have some experience with kotlin - or are at least interested in working and co-maintaining a kotlin code base?

Or - in case you had a different idea in mind - how would you see the collaboration?

**Comment by ursjoss** [comment]
Hi @fastluca 

Nice to hear back from you. Hope you're doing good with your MBA and Corona and all the challenges life has in stock for us in recent days.

Sure, sounds like a plan. Do you have some particular tasks in mind? Stuff you'd like to implement?

In KRis, I'm currently not putting in too much work, except for keeping the dependencies up to date. Next major challange will be to move from bintray to maven central for publishing.

What are your ideas?

**Comment by fastluca** [comment]
Hello,
my MBA is finished and I hope that Corona will also finish as soon as possible!
I saw rapidly what you did and I think it is a great job. Maybe we can work on two tasks:

  *   Increase the tests code coverage
  *   Publish the library on maven

I don't know if from a RIS standard point of view there are some capabilities not implemented yet that we can include in the library.

Gianluca

________________________________
Da: Urs Joss <notifications@github.com>
Inviato: lunedì 8 marzo 2021 16:56
A: fastluca/JRis <JRis@noreply.github.com>
Cc: Gianluca Colaianni <fast_luca@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [fastluca/JRis] Additional contribution (#6)


Hi @fastluca<https://github.com/fastluca>

Nice to hear back from you. Hope you're doing good with your MBA and Corona and all the challenges life has in stock for us in recent days.

Sure, sounds like a plan. Do you have some particular tasks in mind? Stuff you'd like to implement?

In KRis, I'm currently not putting in too much work, except for keeping the dependencies up to date. Next major challange will be to move from bintray to maven central for publishing.

What are your ideas?
